### ISSUE TITLE
TwitterDownloarder.jar cannot access file

### ISSUE THREAD

**Issue by xin-wang-kr** [pan-webis-de/pan-code#6]
Hi dear PAN organizer.

I am trying to use Author Profiling 2016 data to do a research. Recently I used the TwitterDownloader.jar, the download tool to download the tweet texts, however, I cannot successfully proceed the downloading process. It showed that the twitter link is null as the screenshot. 

<img width="513" alt="image" src="https://github.com/pan-webis-de/pan-code/assets/28020765/ed1d7a8b-8f2c-4373-a02c-d943bae78238">

Is there any other alternative way that I can use to download the tweet text data? Look forward to your response. Thanks in advance.

**Comment by kicorangel** [comment]
Dear Xin,

The downloader will not work anymore since Twitter has moved to X and the API has been deprecated.

Best,
Francisco Rangel

**Comment by xin-wang-kr** [comment]
> Dear Xin,
> 
> The downloader will not work anymore since Twitter has moved to X and the API has been deprecated.
> 
> Best, Francisco Rangel

Thank you so much for your reply. So I cannot download the data any more? Do we have any alternative solution?
